#!/usr/bin/env sh

# Conditional reviews based on file changes.
# Detect changes between head and previous commit.
eval "$(scripts/detect-changes.sh HEAD~1 HEAD 2> /dev/null)"
echo "Running conditional checks based on file changes..."

# Always run review for code quality
pnpm review

# Conditional Node checks
if [ "$HAS_FRONTEND_CHANGES" = "true" ]; then
  pnpm build
fi

if [ "$HAS_TEST_CHANGES" = "true" ]; then
  pnpm test
fi

# Conditional Rust checks
if [ "$HAS_RUST_CHANGES" = "true" ]; then
  cargo build
  cargo check
  cargo test
fi
