name: review

on:
  pull_request: { branches: ["main"] }

jobs:
  pnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10 }

      - run: pnpm install
      - run: pnpm review
      - run: pnpm test
      - run: pnpm build

  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Tauri prerequisites on Linux (Debian/Ubuntu).
      # see https://tauri.app/start/prerequisites/#linux
      - run: sudo apt-get update
      - run: sudo apt-get install
          libwebkit2gtk-4.1-dev
          build-essential
          curl
          wget
          file
          libxdo-dev
          libssl-dev
          libayatana-appindicator3-dev
          librsvg2-dev

      - run: cargo check
      - run: cargo test
